account/urls.py
from django.conf.urls import url, include
from django.conf import settings
from . import views
from django.contrib.auth import views as auth_views  # 内置视图文件，重命名auth_views

urlpatterns = [
    #url(r'^login/$', views.user_login, name='user_login'), # 自定义登录
    url(r'^login/$', auth_views.login, name='user_login'),  # django内置登录
    url(r'^new-login/$', auth_views.login, {"template_name":"account/login.html"}),  # 以字典类型向login传入参数
    url(r'^logout/$', auth_views.logout, {"template_name":"account/logout.html"},name="user_logout" ),
    url(r'^register/$', views.register, name="user_register" ),
    # 修改密码
    url(r'^password-change/$', auth_views.password_change,{"post_change_redirect":"/account/password-change-done"}, name="password_change" ),
    url(r'^password-change-done/$', auth_views.password_change_done, name="password_change_done" ),
    # 重置密码
    url(r'^password-reset/$', auth_views.password_reset, {"template_name": "account/password_reset_form.html",
                                                          "email_template_name": "account/password_reset_email.html",
                                                          "post_reset_redirect": "/account/password-reset-done"},
        name="password_reset"),
    url(r'^password-reset-done/$', auth_views.password_reset_done,
        {"template_name": "account/password_reset_done.html"}, name="password_reset_done"),
    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$', auth_views.password_reset_confirm,
        {"template_name": "account/password_reset_confirm.html",
         "post_reset_redirect": "/account/password-reset-complete"}, name="password_reset_confirm"),
    url(r'^password-reset-complete/$', auth_views.password_reset_complete,
        {"template_name": "account/password_reset_complete.html"}, name="password_reset_complete"),
]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # name: 在写模板时,name能直接调用url:{{ blog:blog_title }},name不能重复
    url(r'^$', views.blog_title, name='blog_title'),
    url(r'(?P<article_id>\d)/$', views.blog_article, name='blog_detail'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
]

account/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True)
    birth = models.DateTimeField(blank=True, null=True)
    phone = models.CharField(max_length=20, null=True)

    def __str__(self):
        return 'user {}'.format(self.user.username)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import  timezone
# Create your models here.

class BlogArticles(models.Model):
    """ 博客文章models """
    title =  models.CharField(max_length=300,verbose_name="主题")
    author = models.ForeignKey(User, related_name='blog_posts',verbose_name="作者")  # related_name属性定义名称(related_name是关联对象反向引用描述符)
    body = models.TextField(verbose_name="文章主体")
    publish = models.DateTimeField(default=timezone.now,verbose_name="出版时间")

    class Meta:
        ordering = ('-publish',)  # 以出版时间倒序展示

    def __str__(self):
        return self.title  # 显示标题字符串

account/forms.py
#!/usr/local/bin/python3
#coding=utf-8
#Author: www.xtrdb.net

from django import forms
from django.contrib.auth.models import User # django默认用户模型User类 #p63
from .models import UserProfile

class LoginForm(forms.Form):
    '''
    用户登录表单
    forms.Form不会修改数据库
    '''
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegistrationForm(forms.ModelForm):
    '''
    用户注册
    forms.ModelForm会修改数据库 #p63
    '''
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm Pssword", widget=forms.PasswordInput)

    class Meta:
        '''
        内部类,声明表单所应用的数据模型，也就是将来表单中的数据写入数据库表或修改某些字段值
        '''
        model = User
        fields = ("username", "email")   # 所选用的字段

    def clean_password2(self):
        '''
        重新定义密码，且比对用户输入密码
        :return:
        '''
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("passwords do not match.")
        return cd['password2']

class UserProfileForm(forms.ModelForm):
    '''
    增加注册要求字段
    '''
    class Meta:
        model = UserProfile
        fields = ("phone", "birth")

account/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login  # 内置用户认证和管理应用中引入的两个方法
from .forms import LoginForm, RegistrationForm, UserProfileForm

# Create your views here.

def user_login(request):
    """ 用户登录验证视图 """
    if request.method == 'POST':
        login_form = LoginForm(request.POST)  # request.POST得到提交表单数据，是一个类字典对象
        if login_form.is_valid():  # 验证表单信息
            cd = login_form.cleaned_data  # 以字典的形式返回实例的具体数据，即经过校验之后的属性及其值
            user = authenticate(username=cd['username'], password=cd['password']) # 1
            if user:
                login(request, user)  # 以1所得的user实例对象作为参数，实现用户登录
                return HttpResponse('Welcome You. You have been authenticated successfully')
            else:
                return HttpResponse('Invalid login')
    if request.method == 'GET':
        login_form = LoginForm()   # 第一次向server发出含有表单页面的请求，然后反馈前端页面，等待用户输入
        return render(request, 'account/login.html', {'form': login_form})

def register(request):
    """ 用户注册视图 """
    if request.method == "POST":
        user_form = RegistrationForm(request.POST)
        userprofile_form = UserProfileForm(request.POST)
        if user_form.is_valid() * userprofile_form.is_valid():
            new_user = user_form.save(commit=False)  # 将表单数据保存到数据库，并生成数据对象;commit=False 仅仅生成数据对象
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            new_profile = userprofile_form.save(commit=False)
            new_profile.user = new_user
            new_profile.save()
            return HttpResponse("successfully")
        else:
            return HttpResponse("sorry,your can't register.")
    else:
        user_form = RegistrationForm()
        userprofile_form = UserProfileForm()
        connext = {"form": user_form, "profile": userprofile_form}
        return render(request, "account/rigister.html", connext)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogArticles
# Create your views here.

def blog_title(request):
    ''' 打印文章标题 '''
    blogs = BlogArticles.objects.all()
    """
    >>> from blog.models import  BlogArticles
    >>> test = BlogArticles.objects.all()
    >>> for n in test:
    ...     print(n.id,n)
    ...
    1 面向对象的高级用法
    3 文件处理及异常
    2 装饰器
    """
    context = {"blogs":blogs}
    return render(request, 'blog/title.html', context)

def blog_article(request, article_id):
    ''' 博客文章 '''
    article = get_object_or_404(BlogArticles,id=article_id)
    pub = article.publish
    context = {'article':article, 'publish':pub}
    return render(request,'blog/content.html', context)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
    <head>
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1">
    	<title>{% block title %}{% endblock %}</title>
    	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        {# rel="stylesheet" 描述了当前页面与href所指定文档的关系.即说明的是,href连接的文档是一个新式表 #}
    </head>
    <body>
        {% include "header.html" %}
        <div class="container"> {# 内容居中 #}
        	{% block content %}{% endblock %}
        </div>
        {% include "footer.html" %}
        {% block javascritp %}{% endblock %}
    </body>
</html>

templates/blog/content.html
{% extends "base.html" %}
{% block title %}Blog | Article{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
	<h1>{{ article.title }}</h1>
</div>
<div class="row">
	<div class="col-xs-12 col-md-8">
		<p class="text-center">
            <span>{{ article.author.username }}</span>
            <span style="margin-left: 20px">{{ article.publish }}</span>
        </p>
		<div>{{ article.body }}</div>
	</div>
	<div class="col-xs-6 col-md-4">
		<h2>奋斗</h2>
		<p>Study Python：www.xtrdb.net</p>
{#		<img width="200px" src="http://www.mrwallpaper.com/wallpapers/Fluffy-Cat.jpg">#}
        <img width="170px" src="https://assets.about.me/background/users/z/h/a/zhagyilig_1497628429_085.jpg">
	</div>
</div>
{% endblock %}

templates/blog/title.html
{% extends "base.html" %}
{% block title %}Blog | Titles{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
{# row中使图片或者文字垂直居中 #}
	<h1>我的博客</h1>
</div>
<div class="row">
	<div class="col-xs-12 col-md-8">
    {# 屏幕大于(≥992px) ，使用col-md-* #}
		<ul>
			{% for blog in blogs %}
			<li><a href="{{ blog.id }}">{{ blog.title }}</a></li>
			{% endfor %}
		</ul>
	</div>
	<div class="col-xs-6 col-md-4">
		<h2>努力</h2>
		<p>Study Python：www.xtrdb.net</p>
		<img width="200px" src="http://www.mrwallpaper.com/wallpapers/Fluffy-Cat.jpg">
	</div>
</div>
{% endblock %}

templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">copy right www.xtrdb.net</p>
</div>

templates/header.html
{% load staticfiles %}
<div class="container"> {# 显示居中 #}
    <nav class="navbar navbar-default" role="navigation"> {# 导航栏 #}
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.xtrdb.net"><img src="{% static '/images/logo.png' %}" width="100px"></a>
	    </div> {# 向 <div> 元素添加一个标题 class .navbar-header，内部包含了带有 class navbar-brand 的 <a> 元素。这会让文本看起来更大一号。 #}
	    <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'blog:blog_title' %}">BLOG</a></li>
            </ul> {# 向导航栏添加链接，只需要简单地添加带有 class .nav、.navbar-nav 的无序列表即可 #}
            <ul class="nav navbar-nav navbar-right" style="margin-right: 10px">
                {% if user.is_authenticated %}
                <li>
                    <div class="dropdown" style="margin-top:8px">
                        <button class='btn btn-default dropdown-toggle' type='button' id='dropdownMenu' data-toggle='dropdown'>
                            {{ user.username }}<span class='caret'></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                        </ul>
                    </div>
                </li>
                    <li><a href="{% url 'account:user_logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'account:user_login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>
<script src="{% static 'js/jquery.js'%}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>